"""소액 실주문 검증용 테스트 주문안 JSON 생성 ([긴급-MVP]).

JSON 파일만 생성한다. KIS, live-approve, execute, Telegram 호출 없음.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from deepsignal.live_trading.live_order_executor import load_live_order_plan, validate_live_order_plan
from deepsignal.live_trading.utils.time_utils import daily_ai_timestamp_fields, now_kst_iso


DEFAULT_OUTPUT_NAME = "test_live_order_plan.json"
GENERATED_BY = "test_order_plan"


@dataclass
class SmallLiveOrderPlanInput:
    symbol: str
    quantity: int = 1
    limit_price: float = 0.0
    max_order_value: float = 100_000.0
    output_dir: str = "outputs"
    currency: str = "KRW"


def validate_test_order_plan_inputs(
    *,
    symbol: str,
    quantity: int,
    limit_price: float,
    max_order_value: float,
) -> list[str]:
    errors: list[str] = []
    sym = str(symbol or "").strip().upper()
    if not sym:
        errors.append("symbol is required")
    qty = int(quantity)
    if qty < 1:
        errors.append("quantity must be >= 1")
    if qty > 1:
        errors.append("quantity must be 1 for test plan (max_orders=1)")
    price = float(limit_price)
    if price <= 0:
        errors.append("limit_price must be > 0")
    max_val = float(max_order_value)
    if max_val <= 0:
        errors.append("max_order_value must be > 0")
    estimated = price * qty
    if not errors and estimated > max_val:
        errors.append(
            f"estimated_order_value {estimated:,.0f} exceeds max_order_value {max_val:,.0f}"
        )
    return errors


def build_test_order_plan_payload(config: SmallLiveOrderPlanInput) -> dict[str, Any]:
    errors = validate_test_order_plan_inputs(
        symbol=config.symbol,
        quantity=config.quantity,
        limit_price=config.limit_price,
        max_order_value=config.max_order_value,
    )
    if errors:
        raise ValueError("; ".join(errors))

    sym = str(config.symbol).strip().upper()
    qty = int(config.quantity)
    price = float(config.limit_price)
    estimated_value = price * qty
    plan_date = date.today().isoformat()

    order: dict[str, Any] = {
        "symbol": sym,
        "side": "BUY",
        "order_type": "LIMIT",
        "target_weight": 1.0,
        "target_value": estimated_value,
        "estimated_price": price,
        "estimated_qty": qty,
        "limit_price": price,
        "estimated_order_value": estimated_value,
        "quantity": qty,
        "reason": "test_order_plan: small live execution validation",
        "warnings": ["operator test plan only", "SELL and market orders are not allowed"],
    }

    payload: dict[str, Any] = {
        "date": plan_date,
        "status": "PENDING_APPROVAL",
        "approval_required": True,
        "dry_run": True,
        "generated_by": GENERATED_BY,
        "capital": estimated_value,
        "investable_cash": estimated_value,
        "cash_buffer": 0.0,
        "currency": str(config.currency or "KRW"),
        "max_orders": 1,
        "orders": [order],
        "warnings": [
            "Test order plan for Telegram approval and execute-last-approved validation only.",
            "Not generated by daily-ai-trade-plan.",
            "Real execution still requires terminal execute-last-approved with all live guards.",
        ],
        "safety_boundary": {
            "kis_called": False,
            "live_approve_called": False,
            "execute_last_approved_called": False,
            "telegram_called": False,
            "market_order_allowed": False,
            "sell_allowed": False,
        },
    }
    payload.update(daily_ai_timestamp_fields())
    return payload


def write_test_order_plan(
    config: SmallLiveOrderPlanInput,
    *,
    filename: str = DEFAULT_OUTPUT_NAME,
) -> Path:
    root = Path(config.output_dir).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    path = root / filename
    payload = build_test_order_plan_payload(config)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    plan = load_live_order_plan(path)
    ok, plan_errors = validate_live_order_plan(plan)
    if not ok:
        path.unlink(missing_ok=True)
        raise ValueError(f"generated plan failed validation: {'; '.join(plan_errors)}")

    return path


def format_test_order_plan_console(path: Path, payload: dict[str, Any]) -> str:
    order = (payload.get("orders") or [{}])[0]
    return "\n".join(
        [
            "DeepSignal test order plan created",
            f"Path: {path.as_posix()}",
            f"Symbol: {order.get('symbol')}",
            f"Side: {order.get('side')}",
            f"Order type: {order.get('order_type')}",
            f"Quantity: {order.get('quantity')}",
            f"Limit price: {order.get('limit_price')}",
            f"Estimated order value: {order.get('estimated_order_value')}",
            f"Status: {payload.get('status')}",
            f"Generated at: {payload.get('generated_at', now_kst_iso())}",
            "Next:",
            f"  python main.py telegram-approval-request --plan {path.as_posix()} --send --output-dir {path.parent.as_posix()}",
        ]
    )
